# Write SQL queries to perform the following tasks using the Sakila database:
# List the number of films per category.
SELECT category_id, COUNT(film_id)
FROM film_category
GROUP BY category_id;

# Retrieve the store ID, city, and country for each store.
SELECT store_id, city, country
FROM store
INNER JOIN address
USING (address_id)
INNER JOIN city
USING (city_id)
INNER JOIN country
USING (country_id)
GROUP BY store_id;

# Calculate the total revenue generated by each store in dollars.
SELECT store_id, SUM(amount)
FROM store
INNER JOIN customer
USING (store_id)
INNER JOIN payment
USING (customer_id)
GROUP BY store_id;

# Determine the average running time of films for each category.
SELECT category_id, name, AVG(length)
FROM film_category
INNER JOIN film
USING (film_id)
INNER JOIN category
USING (category_id)
GROUP BY category_id
ORDER BY AVG(length);

